site_name: CLIMBER-X-docs
nav:
    - Home: index.md
    - Getting started:
      - Getting started: getting-started.md
      - Installation: installation.md
      - Usage: usage.md
      - Dependencies: dependencies.md
      - Quick start: quick-start.md
    - Use cases:
      - Pre-industrial spinup: use-cases/01-pi_spinup/index.md
      - Historical: use-cases/02-historical/index.md
    - Output description: 
      - Output files:    var_lists/index.md
    - Workshops:
      - Workshop 2025: workshops/2025/index.md
    - GitHub CLIMBER-X: https://github.com/cxesmc/climber-x

#theme: mkdocs
theme:
    name: readthedocs

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

